language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      
  - "3.7"
  - "3.8"
env:
  - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR
# command to install dependencies
install:
  - pip install coverage
  - pip install requests
# command to run tests
script:
  - coverage run --source=Tea -m pytest tests/test_*
  - wget --no-check-certificate https://codecov.io/bash -O codecov.sh
  - bash codecov.sh -cF "python"